// <auto-generated />
namespace WebserviceColumbus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rating_Add_UserID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rating_Add_UserID));
        
        string IMigrationMetadata.Id
        {
            get { return "201506151139598_Rating_Add_UserID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
