// <auto-generated />
namespace WebserviceColumbus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Travelogue_published : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Travelogue_published));
        
        string IMigrationMetadata.Id
        {
            get { return "201505291347388_Travelogue_published"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
